// Generated by tools/gen.py from tokens/motion.json: edit that, not this.
#pragma once

#include "morph.hpp"
#include "presence.hpp"

namespace motion::tokens {

// A card out of the bar and back (a mix of pop, drip and snappy: B's landing at A's speed)
inline PresenceSpec card() {
    PresenceSpec s;
    s.channels[0] = ChannelSpec{Leg{Spring::fromDuration(0.2992, 0.3), 0.0}, Leg{Spring::fromDuration(0.2094, 0.0), 0.0}, 1.0, 0.15}; // along
    s.channels[1] = ChannelSpec{Leg{Spring::fromDuration(0.2244, 0.2), 0.0}, Leg{Spring::fromDuration(0.2244, 0.0), 0.04}, 1.0, 0.06}; // away
    s.channels[2] = ChannelSpec{Leg{Spring::fromDuration(0.18, 0.0), 0.02}, Leg{Spring::fromDuration(0.2, 0.0), 0.03}, 1.0, 0.0}; // content
    s.channels[3] = ChannelSpec{Leg{Spring::fromDuration(0.12, 0.0), 0.0}, Leg{Spring::fromDuration(0.26, 0.0), 0.07}, 1.0, 0.0}; // glass
    s.anticipation.amount = 0.02;
    s.anticipation.time   = 0.09;
    return s;
}

// A card that isn't attached to the bar: grows a little where it is
inline PresenceSpec cardInPlace() {
    PresenceSpec s;
    s.channels[0] = ChannelSpec{Leg{Spring::fromDuration(0.4, 0.0), 0.0}, Leg{Spring::fromDuration(0.34, 0.0), 0.0}, 1.0, 0.9}; // along
    s.channels[1] = ChannelSpec{Leg{Spring::fromDuration(0.4, 0.0), 0.0}, Leg{Spring::fromDuration(0.34, 0.0), 0.0}, 1.0, 0.9}; // away
    s.channels[2] = ChannelSpec{Leg{Spring::fromDuration(0.2, 0.0), 0.0}, Leg{Spring::fromDuration(0.2, 0.0), 0.0}, 1.0, 0.0}; // content
    s.channels[3] = ChannelSpec{Leg{Spring::fromDuration(0.12, 0.0), 0.0}, Leg{Spring::fromDuration(0.22, 0.0), 0.04}, 1.0, 0.0}; // glass
    s.anticipation.amount = 0.0;
    s.anticipation.time   = 0.09;
    return s;
}

// The rim's flash when a window takes focus: a kick from rest, up in 80 ms
inline Spring focusFlash() { return Spring::fromDuration(0.5027, 0.0); }
// The lock screen's glass forming
inline Spring lockForm() { return Spring::fromDuration(0.42, 0.0); }
// The gleam easing in and out with focus
inline Spring focusFade() { return Spring::fromDuration(0.6, 0.0); }
// Glass giving under a press: a kick from rest that swells and wobbles back (a quarter of its height at most)
inline Spring pressBulge() { return Spring::fromDuration(0.42, 0.35); }

// A morph's channels: near / far / sides: how far each edge has come from the
// seed (0) to the card (1); source: the waist between the bar and the card (0 none, 1 widest);
// scale: the content's scale from geometry.contentFrom (0) to 1 (1); alpha: the
// content's opacity (its blur goes with it); glass: how formed the lens is; fall:
// how far past its place the card hangs (of geometry.fall; negative: up).
namespace ch { enum : int { Near, Far, Sides, Source, Scale, Alpha, Glass, Fall, Count }; } // ch::Near ...

struct MorphGeometry {
    double seedAlong, seedAway; // in place: the seed is the card times these; from the bar: seedAway is how deep in the bar it starts (of its thickness)
    double sourceWidth, sourceInset; // from the bar: the seed's width along the bar, logical px (inset: unused)
    double neck;        // logical px of smooth union between the bar's edge and the card
    double contentFrom; // the content's scale at scale 0
    double blur;        // logical px of content blur at alpha 0
    double fall;        // logical px the card hangs past its place at fall 1
    double waist, waistMax; // the waist at its widest: of the card's width, at most waistMax logical px
    double waistHold, waistSnap; // hold: < 1 keeps the waist thick until late; snap: the waist value it breaks at (0: it melts, never breaks)
};

// A: late snap. A card that drips out of the bar: a bulge pushes out of the bar's edge at the item, the card grows out of it and falls a little past its place, hanging from the bar by an hourglass waist that thins, pinches and snaps; the card springs back up into place with a small wobble and the bar's stub draws back. The content only scales evenly, fades and unblurs. Closing is the join: the content leaves, the card reaches up, a thread forms, widens into a waist, and the card flows back into the bar. The waist keeps its thickness almost to the end, then pinches and snaps within a couple of frames.
inline MorphSpec island() {
    MorphSpec s;
    s.count = 8;
    s.tracks[ch::Near] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.24, 0.0), 1.0}}, {Step{0.1, Spring::fromDuration(0.22, 0.0), 0.0}});
    s.tracks[ch::Far] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.36, 0.26), 1.0}}, {Step{0.09, Spring::fromDuration(0.26, 0.0), 0.0}});
    s.tracks[ch::Sides] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.14), 1.0}}, {Step{0.0, Spring::fromDuration(0.22, 0.0), 0.0}});
    s.tracks[ch::Source] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.1, 0.0), 1.0}, Step{0.2, Spring::fromDuration(0.2, 0.0), 0.0}}, {Step{0.03, Spring::fromDuration(0.12, 0.0), 1.0}, Step{0.26, Spring::fromDuration(0.14, 0.0), 0.0}});
    s.tracks[ch::Scale] = Track::make(0.0, {Step{0.03, Spring::fromDuration(0.34, 0.12), 1.0}}, {Step{0.0, Spring::fromDuration(0.2, 0.0), 0.0}});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.07, Spring::fromDuration(0.22, 0.0), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 0.0}});
    s.tracks[ch::Glass] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.1, 0.0), 1.0}}, {Step{0.27, Spring::fromDuration(0.12, 0.0), 0.0}});
    s.tracks[ch::Fall] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.2, 0.0), 1.0}, Step{0.24, Spring::fromDuration(0.34, 0.3), 0.0}}, {Step{0.0, Spring::fromDuration(0.16, 0.0), -0.25}, Step{0.12, Spring::fromDuration(0.2, 0.0), 0.0}});
    return s;
}
inline MorphGeometry islandGeometry() { return {0.7, 0.5, 56, 0, 20, 0.86, 10, 28, 0.42, 150, 0.3, 0.12}; }

// B: melt. Open: the card drips out of the bar and pulls the waist long; the waist pinches and snaps, then the card settles into place (~0.5 s, starting at once). Close: a small swell, then the card drains back into the bar through its waist, staying connected, its content shrinking with it.
inline MorphSpec islandMelt() {
    MorphSpec s;
    s.count = 8;
    s.tracks[ch::Near] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.192, 0), 1.0}}, {Step{0.176, Spring::fromDuration(0.176, 0), 0.0}});
    s.tracks[ch::Far] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.272, 0.16), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 1.06}, Step{0.112, Spring::fromDuration(0.304, 0.0), 0.0}});
    s.tracks[ch::Sides] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.224, 0.1), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 1.06}, Step{0.08, Spring::fromDuration(0.272, 0.0), 0.0}});
    s.tracks[ch::Source] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.08, 0), 1.0}, Step{0.08, Spring::fromDuration(0.24, 0), 0.0}}, {Step{0.0, Spring::fromDuration(0.064, 0), 1.0}, Step{0.384, Spring::fromDuration(0.112, 0), 0.0}});
    s.tracks[ch::Scale] = Track::make(0.0, {Step{0.024, Spring::fromDuration(0.256, 0), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 1.04}, Step{0.08, Spring::fromDuration(0.32, 0.2), 0.0}});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.048, Spring::fromDuration(0.16, 0), 1.0}}, {Step{0.112, Spring::fromDuration(0.24, 0), 0.0}});
    s.tracks[ch::Glass] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.08, 0), 1.0}}, {Step{0.4, Spring::fromDuration(0.112, 0), 0.0}});
    s.tracks[ch::Fall] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.144, 0), 1.0}, Step{0.248, Spring::fromDuration(0.256, 0), 0.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 0.22}, Step{0.08, Spring::fromDuration(0.24, 0.0), 0.0}});
    return s;
}
inline MorphGeometry islandMeltGeometry() { return {0.7, 0.5, 56, 0, 20, 0.86, 4, 28, 0.3, 100, 0.7, 0.2}; }

// C: thick and bouncy. A wider waist and a deeper hang; the waist keeps its thickness until late and snaps, and the card bounces up into place with a visible wobble.
inline MorphSpec islandBouncy() {
    MorphSpec s;
    s.count = 8;
    s.tracks[ch::Near] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.24, 0.0), 1.0}}, {Step{0.1, Spring::fromDuration(0.22, 0.0), 0.0}});
    s.tracks[ch::Far] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.36, 0.26), 1.0}}, {Step{0.09, Spring::fromDuration(0.26, 0.0), 0.0}});
    s.tracks[ch::Sides] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.14), 1.0}}, {Step{0.0, Spring::fromDuration(0.22, 0.0), 0.0}});
    s.tracks[ch::Source] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.1, 0.0), 1.0}, Step{0.24, Spring::fromDuration(0.2, 0.0), 0.0}}, {Step{0.03, Spring::fromDuration(0.12, 0.0), 1.0}, Step{0.26, Spring::fromDuration(0.14, 0.0), 0.0}});
    s.tracks[ch::Scale] = Track::make(0.0, {Step{0.03, Spring::fromDuration(0.34, 0.12), 1.0}}, {Step{0.0, Spring::fromDuration(0.2, 0.0), 0.0}});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.07, Spring::fromDuration(0.22, 0.0), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 0.0}});
    s.tracks[ch::Glass] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.1, 0.0), 1.0}}, {Step{0.27, Spring::fromDuration(0.12, 0.0), 0.0}});
    s.tracks[ch::Fall] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.22, 0.0), 1.0}, Step{0.27, Spring::fromDuration(0.42, 0.45), 0.0}}, {Step{0.0, Spring::fromDuration(0.16, 0.0), -0.25}, Step{0.12, Spring::fromDuration(0.2, 0.0), 0.0}});
    return s;
}
inline MorphGeometry islandBouncyGeometry() { return {0.7, 0.5, 56, 0, 20, 0.86, 10, 40, 0.55, 210, 0.45, 0.12}; }

// A card that isn't attached to the bar (the menu, a dialog): it swells out of a smaller rounded shape where it is, the height a touch behind the width (the jelly), the content scaling in evenly behind it; closing, the content goes first and the glass flattens as it gathers in.
inline MorphSpec islandInPlace() {
    MorphSpec s;
    s.count = 8;
    s.tracks[ch::Near] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.34, 0.2), 1.0}}, {Step{0.03, Spring::fromDuration(0.24, 0.0), 0.0}});
    s.tracks[ch::Far] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.34, 0.2), 1.0}}, {Step{0.03, Spring::fromDuration(0.24, 0.0), 0.0}});
    s.tracks[ch::Sides] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.12), 1.0}}, {Step{0.04, Spring::fromDuration(0.24, 0.0), 0.0}});
    s.tracks[ch::Source] = Track::make(0.0, {}, {});
    s.tracks[ch::Scale] = Track::make(0.0, {Step{0.02, Spring::fromDuration(0.32, 0.1), 1.0}}, {Step{0.0, Spring::fromDuration(0.2, 0.0), 0.0}});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.04, Spring::fromDuration(0.2, 0.0), 1.0}}, {Step{0.0, Spring::fromDuration(0.08, 0.0), 0.0}});
    s.tracks[ch::Glass] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.1, 0.0), 1.0}}, {Step{0.08, Spring::fromDuration(0.18, 0.0), 0.0}});
    s.tracks[ch::Fall] = Track::make(0.0, {}, {});
    return s;
}
// With animations off (less motion wanted): no pour, no zoom, the card fades in and
// out where it is (critically damped, no overshoot)
inline MorphSpec islandFade() {
    MorphSpec s;
    s.count = 8;
    for (int k : {ch::Near, ch::Far, ch::Sides, ch::Scale})
        s.tracks[k] = Track::make(1.0, {}, {});
    s.tracks[ch::Source] = Track::make(0.0, {}, {});
    s.tracks[ch::Fall] = Track::make(0.0, {}, {});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.16, 0.0), 1.0}}, {Step{0.0, Spring::fromDuration(0.1, 0.0), 0.0}});
    s.tracks[ch::Glass] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.12, 0.0), 1.0}}, {Step{0.03, Spring::fromDuration(0.12, 0.0), 0.0}});
    return s;
}
inline MorphGeometry islandInPlaceGeometry() { return {0.82, 0.7, 0, 0, 0, 0.92, 8, 0, 0, 0, 1.0, 0.0}; }

// From one card straight into another (a menu opened while another is open): one
// piece of glass that changes its mind. It starts as the open card, exactly where
// and as big as it is, and every edge travels to the new card on the same spring
// (no drip, no neck, no fall: it never goes back into the bar); the glass is there
// from the first frame, the new content comes in over it. Only the show scripts are
// used: a close during it re-bases onto the bar's own spec first.
inline MorphSpec islandSwitch() {
    MorphSpec s;
    s.count = 8;
    s.tracks[ch::Near] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.06), 1.0}}, {});
    s.tracks[ch::Far] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.06), 1.0}}, {});
    s.tracks[ch::Sides] = Track::make(0.0, {Step{0.0, Spring::fromDuration(0.3, 0.06), 1.0}}, {});
    s.tracks[ch::Source] = Track::make(0.0, {}, {});
    s.tracks[ch::Scale] = Track::make(0.65, {Step{0.0, Spring::fromDuration(0.28, 0.04), 1.0}}, {});
    s.tracks[ch::Alpha] = Track::make(0.0, {Step{0.03, Spring::fromDuration(0.16, 0.0), 1.0}}, {});
    s.tracks[ch::Glass] = Track::make(1.0, {}, {});
    s.tracks[ch::Fall] = Track::make(0.0, {}, {});
    return s;
}
inline MorphGeometry islandSwitchGeometry() { return {0.7, 0.5, 56, 0, 0, 0.86, 4, 0, 0.3, 100, 0.7, 0.2}; }

// The active window's light runs round its own outline at one speed on a rounded path (pathRadius); it stands distance logical px out from the glass and comes in to cornerDistance round each corner (eased over cornerSpan of path), so the lit stretch narrows into the corner and widens out of it: swung round the corner at full distance, the next edge's whole stretch lit up at once (it read as leaving the corner too fast)
inline constexpr double gleamEdgeSpeed  = 450; // logical px/s: the comet's speed along the rim
inline constexpr double gleamCometLength = 90; // logical px: the comet's length (one sigma either side)
inline constexpr double gleamTwinSpeed = 300; // logical px/s: the twin streaks' speed
inline constexpr double gleamTwinLength = 70; // logical px: each twin streak's length (one sigma either side)
inline constexpr double gleamHaloLap = 7.0; // s: the halo's lap, whatever the window's size
inline constexpr double gleamHaloSpread = 0.12; // of the lap: the halo's length (one sigma either side; about half the rim lit)
inline constexpr double gleamAuraLap = 6.0; // s: the aura's crest once round
inline constexpr double gleamAuraSpread = 0.14; // of the lap: the crest (one sigma either side)
inline constexpr double gleamPrismLap = 40.0; // s: the prism's light once round the room

} // namespace motion::tokens
